name: Check size

on:
  pull_request:
    branches:
      - develop

jobs:
  check-size:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    env:
      CI_JOB_NUMBER: 1
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: size-limit-action
        uses: andresz1/size-limit-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}