name: Test

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
#        Broken this step
#         https://github.com/wagoid/commitlint-github-action/issues/755
#      - name: Lint Commit Messages
#        uses: wagoid/commitlint-github-action@v5
      - name: Test
        run: pnpm t
      - name: Build
        run: pnpm build