name: Test

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - uses: ./.github/actions/setup
      - name: Lint Commit Messages
        uses: wagoid/commitlint-github-action@v6
      - name: Test
        run: pnpm t
      - name: Build
        run: pnpm build