name: Test

on:
  push:
    branches:
      - '*'
      - '!main'

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 180
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
      - name: Install Dependencies
        run: npm ci
      - name: Test
        run: |
          npm run test && npm run lint && npm run prettier
      - name: Build
        run: npm run build